package editorialradar

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestValidateAcceptsCompleteFixture(t *testing.T) {
	root := writeFixture(t)

	failures := Validate(root)
	if len(failures) > 0 {
		t.Fatalf("Validate returned failures:\n%s", strings.Join(failures, "\n"))
	}
}

func TestValidateRejectsInvalidSourceURL(t *testing.T) {
	root := writeFixture(t)
	writeFile(t, root, sourcesPath, strings.Replace(validSources(), "https://sre.google/", "http://sre.google/", 1))

	failures := Validate(root)
	assertFailureContains(t, failures, "non-HTTPS source URL")
}

func TestValidateRejectsUnknownSignalField(t *testing.T) {
	root := writeFixture(t)
	writeFile(t, root, signalsPath, `{
  "schema_version": "editorial-research-signals-v1",
  "updated_at": "2026-08-27T00:00:00Z",
  "signals": [],
  "surprise": true
}`)

	failures := Validate(root)
	assertFailureContains(t, failures, "unknown field")
}

func TestValidateRejectsStaleReadmeGuidance(t *testing.T) {
	root := writeFixture(t)
	writeFile(t, root, readmePath, "The Anatole theme lives in themes/anatole as a git submodule.\n")

	failures := Validate(root)
	assertFailureContains(t, failures, "stale Anatole theme/submodule guidance")
}

func writeFixture(t *testing.T) string {
	t.Helper()

	root := t.TempDir()
	writeFile(t, root, contractPath, strings.Join([]string{
		"external sources -> research agent -> research issue -> Ranjib review",
		"Disallowed path",
		"Evidence Hierarchy",
		"Lived-Experience Test",
		"Trend-Chasing Rejection Criteria",
		"Freshness Classes",
		"Research Scoring Rubric",
		"Privacy Rules",
		"Allowed Automated Outputs",
		"Prohibited Autonomous Outputs",
		"Human Approval Boundaries",
		"First Drift Fixture",
	}, "\n"))
	writeFile(t, root, sourcesPath, validSources())
	writeFile(t, root, signalsPath, validSignals())
	writeFile(t, root, workflowPath, strings.Join([]string{
		"engine: codex",
		"workflow_dispatch:",
		"tools:",
		"web-search:",
		"safe-outputs:",
		"create-issue:",
		"Read `docs/editorial-radar.md` first",
		"Do not create articles",
		"Do not modify published content",
	}, "\n"))
	writeFile(t, root, lockPath, strings.Join([]string{
		"# gh-aw-metadata:",
		"This file was automatically generated by gh-aw",
		"agent_id\":\"codex\"",
		"CODEX_API_KEY",
		"OPENAI_API_KEY",
	}, "\n"))
	writeFile(t, root, specPath, strings.Join([]string{
		"Goal",
		"Scope",
		"Architecture",
		"Agentic Workflow MVP",
		"Non-Goals",
	}, "\n"))
	writeFile(t, root, planPath, strings.Join([]string{
		"REQUIRED SUB-SKILL",
		"Task 1",
		"Task 2",
		"Task 3",
		"Task 4",
		"Task 5",
		"hugo --gc --minify",
		"go test ./...",
		"go run ./cmd/validate-editorial-radar",
	}, "\n"))
	writeFile(t, root, readmePath, strings.Join([]string{
		"There is no Hugo theme submodule.",
		"docs/systems-in-practice-hub.md",
	}, "\n"))
	return root
}

func writeFile(t *testing.T, root, path, contents string) {
	t.Helper()

	fullPath := filepath.Join(root, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		t.Fatalf("creating fixture directory: %v", err)
	}
	if err := os.WriteFile(fullPath, []byte(contents), 0o644); err != nil {
		t.Fatalf("writing fixture file %s: %v", path, err)
	}
}

func assertFailureContains(t *testing.T, failures []string, want string) {
	t.Helper()

	for _, failure := range failures {
		if strings.Contains(failure, want) {
			return
		}
	}
	t.Fatalf("expected failure containing %q, got:\n%s", want, strings.Join(failures, "\n"))
}

func validSources() string {
	return `schema_version: editorial-research-sources-v1
updated_at: 2026-08-27
authority_levels:
  primary: Official project, vendor, standards, research, or source-owner material.
  ecosystem: High-context ecosystem sources, maintainers, foundations, or major engineering teams.
  practitioner: Detailed practitioner reports with enough evidence to verify.
  secondary: Aggregators, social posts, newsletters, and SEO summaries.
domains:
  sre:
    primary:
      - name: Google SRE
        url: https://sre.google/
        topics: [sre]
      - name: AWS Builders Library
        url: https://aws.amazon.com/builders-library/
        topics: [distributed-systems]
      - name: Cloudflare Blog
        url: https://blog.cloudflare.com/
        topics: [reliability]
      - name: Uber Engineering
        url: https://www.uber.com/blog/engineering/
        topics: [platform-engineering]
  genai:
    primary:
      - name: OpenAI News
        url: https://openai.com/news/
        topics: [models]
      - name: OpenAI Docs
        url: https://platform.openai.com/docs/
        topics: [api]
      - name: Anthropic News
        url: https://www.anthropic.com/news
        topics: [models]
      - name: Google DeepMind Blog
        url: https://deepmind.google/discover/blog/
        topics: [research]
      - name: GitHub Blog
        url: https://github.blog/
        topics: [developer-tools]
    engineering:
      - name: Hugging Face Blog
        url: https://huggingface.co/blog
        topics: [models]
      - name: LangChain Blog
        url: https://blog.langchain.com/
        topics: [agents]
      - name: Promptfoo
        url: https://www.promptfoo.dev/blog/
        topics: [evals]
      - name: Arize Phoenix
        url: https://arize.com/blog/
        topics: [observability]
    research:
      - name: arXiv CL
        url: https://arxiv.org/list/cs.CL/recent
        topics: [language-models]
      - name: arXiv AI
        url: https://arxiv.org/list/cs.AI/recent
        topics: [agents]
  open_source_physical_computing:
    primary:
      - name: Raspberry Pi News
        url: https://www.raspberrypi.com/news/
        topics: [hardware]
      - name: Adafruit Blog
        url: https://blog.adafruit.com/
        topics: [maker]
      - name: Arduino Blog
        url: https://blog.arduino.cc/
        topics: [microcontrollers]
    ecosystem:
      - name: Hackaday
        url: https://hackaday.com/
        topics: [hardware]
  hobbies:
    gardening:
      - name: UC ANR
        url: https://ucanr.edu/
        topics: [gardening]
      - name: UC IPM
        url: https://ipm.ucanr.edu/
        topics: [pests]
      - name: EPA WaterSense
        url: https://www.epa.gov/watersense
        topics: [water]
    overlanding:
      - name: Tread Lightly
        url: https://treadlightly.org/
        topics: [stewardship]
      - name: National Weather Service
        url: https://www.weather.gov/
        topics: [weather]
    reef_keeping:
      - name: reef-pi
        url: https://reef-pi.github.io/
        topics: [automation]
      - name: Reef2Reef
        url: https://www.reef2reef.com/
        topics: [community]
    astronomy:
      - name: NASA Science
        url: https://science.nasa.gov/
        topics: [astronomy]
      - name: AAVSO
        url: https://www.aavso.org/
        topics: [observation]
review_policy:
  prefer_primary_sources: true
  secondary_sources_require_corroboration: true
  explain_lower_authority_influence: true
`
}

func validSignals() string {
	return `{
  "schema_version": "editorial-research-signals-v1",
  "updated_at": "2026-08-27T00:00:00Z",
  "signals": [
    {
      "topic": "agent context lifecycle management",
      "first_seen": "2026-08-27",
      "last_seen": "2026-08-27",
      "occurrences": 0,
      "sources": [],
      "velocity": "seed",
      "editorial_lane": "GenAI practice",
      "related_posts": [],
      "related_issues": [78],
      "status": "watch"
    }
  ]
}`
}
